AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Create Person

  SAM Template for Create Person

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  CreatePersonFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        CreatePerson:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /demo/person
            Method: post
      Policies:
        - AmazonDynamoDBFullAccess
    Metadata:
      DockerTag: java17-maven-v1
      DockerContext: ./CreatePersonFunction
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreatePersonApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Person function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/demo/person/"
  CreatePersonFunction:
    Description: "Create Person Lambda Function ARN"
    Value: !GetAtt CreatePersonFunction.Arn
  CreatePersonFunctionIamRole:
    Description: "Implicit IAM Role created for Create Person function"
    Value: !GetAtt CreatePersonFunctionRole.Arn
